### ISSUE TITLE
new env works

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/config-windows#7]
* Anaconda 2018.12 `python` may experience problem importing `pylab`
* In the [`qtconsole`](https://ipython.org/ipython-doc/3/interactive/qtconsole.html) (also available from Anaconda Navigator), `import pylab` works.
* After creating a new environment, `import pylab` works in `python`.

``` sh
conda env export --file <.yml> --name <env>
conda env create --name <new env> --file <.yml>
conda activate <new env>
```

**Comment by kangwonlee** [comment]
``` sh
$ conda info --envs
# conda environments:
#
base                  *  C:\Users\beachgoer\Anaconda3


beachgoer@DESKTOP-6GHF63B MINGW64 ~/Documents/19pf-reposetman/data/ref/1903pf-lp3thw-template/pylab (master)
$ python sine_graph.py
Traceback (most recent call last):
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sine_graph.py", line 3, in <module>
    import pylab as pl
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 141, in <module>
    from . import cbook, rcsetup
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 33, in <module>
    import numpy as np
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\beachgoer\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
```

**Comment by kangwonlee** [comment]
``` sh
Traceback (most recent call last):
  File "$HOME\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sine_graph.py", line 3, in <module>
    import pylab as pl
  File "$HOME\Anaconda3\lib\site-packages\pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "$HOME\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 141, in <module>
    from . import cbook, rcsetup
  File "$HOME\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 33, in <module>
    import numpy as np
  File "$HOME\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "$HOME\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "$HOME\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "$HOME\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "$HOME\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
```

**Comment by kangwonlee** [comment]
* In MS VS Code, running script after `conda activate base` works
* Need to compare `env` before and after?

**Comment by kangwonlee** [comment]
* After `conda activate base`, followings added to the `$PATH`

**Comment by kangwonlee** [comment]
* It seems that `conda activate base` adds followings to the `$PATH`

```python
{
    '$HOME/Anaconda3/bin', 
    '$HOME/Anaconda3/Library/mingw-w64/bin', 
    '$HOME/Anaconda3/Library/bin', 
    '$HOME/Anaconda3/Library/usr/bin'
}
```

* Among these, adding `$HOME/Anaconda3/Library/bin` to `$PATH` line of `.bashrc` enables `import pylab`

**Comment by kangwonlee** [comment]
* c29b24cd74bf62039847f46a5a2894c2cf825e09 adds the `$HOME/Anaconda3/Library/bin` to `$PATH` line of `.bashrc` 
* To make sure, need a test
* 894f3de8eb400c29691c47658c0c5aad9a5a0a81 attempted but need permission
* Crossing fingers for now
